;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        viper-exit-minibuffer
        viper-find-char-forward
        viper-forward-char
        viper-forward-word
        viper-undo
        viper-next-line
        viper-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        viper-command-argument
        viper-digit-argument
        ))

