(customize-set-variable 'backup-by-copying t)
(customize-set-variable 'kept-new-versions 100)
(customize-set-variable 'kept-old-versions 100)
(customize-set-variable 'vc-make-backup-files t)
(customize-set-variable 'version-control t)
(customize-set-variable 'delete-by-moving-to-trash t)
(defun force-backup-buffer ()
  (let ((buffer-backed-up nil))
    (backup-buffer)))
(add-hook 'before-save-hook 'force-backup-buffer)
